### ISSUE TITLE
Epic for metabattle.com using embeds

### ISSUE THREAD

**Issue by madou** [madou/armory-react#259]
- [x] https://github.com/madou/armory-react/issues/253
- [x] https://github.com/madou/armory-react/issues/248
- [ ] https://github.com/madou/armory-react/issues/232 (stretch goal)

**Comment by valento92** [comment]
From the top of my head, it's #253. I'm also locked on pet skills as they are not available from official API yet, but that isn't a real issue because I can fall back to the old squishy ugly horrible depressive tooltips (the ones we css-coded way back then).

**Comment by valento92** [comment]
An interesting note (and why I chose your tooltips/embeds in the first place): I'll be able to remove all complex SMW usage which slow the wiki a lot, and since you gracefully cache data on localstorage it makes it so much better. 

Funny fact: when skill APIs didn't even exist I sort of created an ugly script to pull data from official wiki and cache locally. Obviously it's not even close to the process you go through because I simply don't know how to code like you do, but it was an attempt waaay back then. The ugly script is on my github, though I'll probably remove it because it's a shame. haha

**Comment by valento92** [comment]
By the way, Metabattle has a [Discord](https://discordapp.com/invite/0jdZWe6xdIy46Yp5) ~~where I usually praise you~~ ahem... and you can reach me there.

**Comment by madou** [comment]
cool! ok

**Comment by valento92** [comment]
[SMW](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki).

**Comment by madou** [comment]
neat

**Comment by madou** [comment]
alright @valento92 you have your base functionality !

**Comment by valento92** [comment]
@madou nice, now I got to carefully do my thing and once I'm done I'll have server admin to swap templates. Probably gonna break the wiki because it's a massive replace command, but yeah... :P

**Comment by madou** [comment]
lol good luck : P
